### ISSUE TITLE
THIS SUCKS (DO NOT DOWNLOAD)

### ISSUE THREAD

**Issue by Shane-222** [DanielSmith1239/HQTriviaMaster#123]
THIS APPLICATION GETS AT THE MOST 2 OUT OF THE 12 QUESTIONS ASKED AT HQ. MADE ME LOSE ON MANY OCCASIONS. MY GUESSING SKILLS ARE MORE IMPRESSIVE THAN THIS HEAP OF TRASH. I HOPE TO SAVE MANY HQ PLAYERS FROM THIS TERRIBLE TRAGEDY.

YOUR HERO,
Jack

**Comment by hmffffff** [comment]
Sounds like you guess real well if you "out on many occasions". Just my opinion tho

**Comment by DanielSmith1239** [comment]
I usually get 2-3 questions wrong, so you definitely didn't set it up correctly. This is just a fun project I made for myself that I decided to share with people. If you don't like it, just don't use it. I don't appreciate you being a dick and degrading my work, especially because I put a lot of time into it. So thank you, and fuck off.
