### ISSUE TITLE
Swift Compiler Errors

### ISSUE THREAD

**Issue by Salopena** [DanielSmith1239/HQTriviaMaster#81]
When trying to build for the first time, I'm met with many compiler errors like in the photo below. Any suggestions?

![screen shot 2018-03-21 at 7 42 58 pm](https://user-images.githubusercontent.com/13756705/37746710-22056dcc-2d41-11e8-8ada-fd80fe877c81.png)

**Comment by tokyoghoul6** [comment]
I had the same issue as well. I fixed it by using the latest version of SwiftWebSocket instead of the one in the Podfile. I don't know if it is the right fix, as the app crashed a lot of time while using WebSocket mode or at time of saving HQ token and other details.

@DanielSmith1239 what is the right fix or this?

**Comment by DanielSmith1239** [comment]
Weird, I never ran into this issue...
Make sure you are running on the latest stable version of Xcode (not beta). Other than that, I'm not completely sure. Maybe just try redownloading everything.

**Comment by Salopena** [comment]
Got it to build by downloading the project as a zip, running pod install, opening the xcworkspace file and running the app. Not sure what went wrong before, maybe because I tried cloning it instead?

**Comment by jamez14** [comment]
I ran into the same issue and followed the instructions from [this GitHub issue](https://github.com/tidwall/SwiftWebSocket/issues/102#issuecomment-346932230). The comment mentioned changing the Podfile to have `pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git', :branch => 'master'` instead of `pod SwiftWebSocket`. It is an issue with Swift 4.

**Comment by spaz926** [comment]
Update your Pod repo with `pod repo update` it takes a while if it has never been done before. Do it again if the HEAD version listed doesn't match the latest on this page: https://github.com/CocoaPods/Specs/commits/master
